added checkaur script + rewrote soundctl and updated license

diff --git a/soundctl b/soundctl
--- a/soundctl
+++ b/soundctl
@@ -1,28 +1,62 @@
 #!/usr/bin/env sh
 
 # ----------------------------------------------------
-# file:     $HOME//scripts/headphone-toggle
+# file:     $HOME/scripts/soundctl
 # author    jls - http://sjorssparreboom.nl
 # ----------------------------------------------------
 
 # Tested with pulseaudio (Server version 9.0)
 
-SINK_NAMES=($(pactl list sinks short | awk '{printf("%s\n", $2 )}'))
-CARD_NAMES=($(pactl list cards short | awk '{printf("%s\n", $2 )}'))
+# Copyright (c) 2013-2016 Sjors Sparreboom
+# The MIT License (MIT) http://opensource.org/licenses/MIT
 
 usage() {
 	cat << EOF 
 
-	soundctl options:
+	NOTES:
+	This program requires that pactl is installed!
 
-	headphone	|  move sink to the external usb headphones
-	speakers        |  move sink to the built-in speakers
+	DESCRIPTION:
+	This program is a wrapper around pactl and tries to make your 
+	life easier by making it less verbose and easier to manage your
+	sound cards and available sinks.
+
+	IMPORTANT!
+
+	THIS PROGRAM REQUIRES THAT YOU SET YOUR 'CARDS', 'PROFILES' AND 'SINKS' AS ENVIRONMENT VARIABLES!
+
+	Your 'sink', 'card' and 'profile' can be found by running 'soundctl {cards,sinks,profiles}'!
+	SEE SOUNDCTL OPTIONS BELOW!
+
+	For this program to work you have to set the following ENVIRONMENT VARIABLES, either
+	in your .zshenv or .profile respectively:
+	  -> DEFAULT_PROFILE
+	  -> DEFAULT_SND_CARD
+	  -> DEFAULT_SINK
+
+	For HDMI support additional VARIABLES are needed:
+	  -> HDMI_PROFILE
+	  -> HDMI_SND_CARD
+	  -> HDMI_SINK
+	
+	Additionally 10 other sound devices can be set.
+	The naming conventions for these ENVIRONMENT VARIABLES, where X is the position of [0-9]:
+	  -> EXTERNAL_PROFILE_0X
+	  -> EXTERNAL_SND_CARD_0X
+	  -> EXTERNAL_SINK_0X
+
+
+	SOUNDCTL OPTIONS:
+
+	external[n]	|  move sink to a external device
+	default         |  move sink to the default device
 	hdmi		|  move sink to the hdmi device
-	volume		|  set the volume of the sinks
+	set-volume	|  set the volume of the sinks
 
-	device          |  give information about the current playing sound handling device
 	profiles	|  overview of all the profile available
-	list            |  list all the sinks
+	cards           |  list card information
+	sinks           |  list sink information
+	volume          |  list volume levels
 
 	restart         |  restart sound server
 	help            |  show this page
@@ -30,66 +64,130 @@ usage() {
 EOF
 }
 
+# set up to 10 different audio devices!
+external() {
+	PROFILE="\$EXTERNAL_PROFILE_0"
+	CARD="\$EXTERNAL_SND_CARD_0"
+	SINK="\$EXTERNAL_SINK_0"
 
-headphone() {
-	# User adjustment here
-	PROFILE="output:analog-stereo+input:analog-mono"
-	SINK_NAME=$(getsinkname "c-media")
-	CARD_NAME=$(getcardname "c-media")
-	# END
+	if (( $# == 1 )); then
+		[[ ! $1 =~ ^[0-9]+$ ]] && printf "%s\n" "Error: Not a valid number" && exit 1;
+		if (( "$1" != 0 )); then
+			PROFILE="\$EXTERNAL_PROFILE_0${1#0}"
+			CARD="\$EXTERNAL_SND_CARD_0${1#0}"
+			SINK="\$EXTERNAL_SINK_0${1#0}"
+		fi
+	fi
 
-	SINK_NR=$(pactl list sinks short | awk -v sink="$SINK_NAME" '{ IGNORECASE = 1; if($2 ~ sink && /running/ || /idle/) { {print $1} ; } ; }')
+	for (( i = 0; i < 10; i++ )); do
+		# results of the evaluations
+		PRSLT=$(eval echo ${PROFILE}${i})
+		CRSLT=$(eval echo ${CARD}${i})
+		SRSLT=$(eval echo ${SINK}${i})
 
-	[[ ! $SINK_NR ]] && initdevice "$CARD_NAME" "$SINK_NAME" "$PROFILE"
+		# check
+		[[ ( ! -z "$CRSLT" && ! -z "$SRSLT" && ! -z "$PRSLT" ) ]] && switch "$CRSLT" "$SRSLT" "$PRSLT"
+	done
 }
 
-speakers() {
-	# User adjustment here
-	PROFILE="output:analog-stereo+input:analog-stereo"
-	SINK_NAME=$(getsinkname "alsa_output.pci-0000_00_1b.0.analog-stereo")
-	CARD_NAME=$(getcardname "alsa_card.pci-0000_00_1b.0")
-	#END
+# switch to the provided device
+# param order:
+# param1 -> card name
+# param2 -> sink name
+# param3 -> profile
+switch() {
+	AVAILABLE=$(pactl list sinks short | awk -v sink="$2" '{ IGNORECASE = 1; if($2 ~ sink && /running/ || /idle/) { {print $1} ; } ; }')
 
-	SINK_NR=$(pactl list sinks short | awk -v sink="$SINK_NAME" '{ IGNORECASE = 1; if($2 ~ sink && /running/ || /idle/) { {print $1} ; } ; }')
-	
-	[[ ! $SINK_NR ]] && initdevice "$CARD_NAME" "$SINK_NAME" "$PROFILE"
+	if [[ -z "$AVAILABLE" ]] && pactl set-card-profile "$1" "$3"; then
+		pactl set-sink-volume "$2" 25% # ! IMPORTANT SO YOUR EAR DRUMS WON'T BLOW UP
+		pactl move-sink-input "$(pactl list sink-inputs short | awk 'NR==1 {print $1}')" "$2"
+	fi
 }
 
+default() {
+	# base environment variables
+	PROFILE="\$DEFAULT_PROFILE"
+	CARD="\$DEFAULT_SND_CARD"
+	SINK="\$DEFAULT_SINK"
+
+	# results of the evaluations
+	PRSLT=$(eval echo ${PROFILE})
+	CRSLT=$(eval echo ${CARD})
+	SRSLT=$(eval echo ${SINK})
+
+	# check
+	[[ ( ! -z "$CRSLT" && ! -z "$SRSLT" && ! -z "$PRSLT" ) ]] && switch "$CRSLT" "$SRSLT" "$PRSLT"
+}
+
+# Special case because there has to be a connection to the display
 hdmi() {
-	# User adjustment here
-	PROFILE="output:hdmi-stereo-extra1"
-	SINK_NAME=$(getsinkname "hdmi")
-	CARD_NAME=$(getcardname "alsa_card.pci-0000_00_03.0")
-	# END
-
+	# base environment variables
+	PROFILE="\$HDMI_PROFILE"
+	CARD="\$HDMI_SND_CARD"
+	SINK="\$HDMI_SINK"
 	HDMI_STAT=$(cat /sys/class/drm/card0/*HDMI*/status)
-	SINK_NR=$(pactl list sinks short | awk -v sink="$SINK_NAME" '{ IGNORECASE = 1; if($2 ~ sink && /running/ || /idle/) { {print $1} ; } ; }')
 
-	[[ ! $HDMI_STAT == connected ]] && [[ $SINK_NR ]] && initdevice "$CARD_NAME" "$SINK_NAME" "$PROFILE"
+	# results of the evaluations
+	PRSLT=$(eval echo ${PROFILE})
+	CRSLT=$(eval echo ${CARD})
+	SRSLT=$(eval echo ${SINK})
+
+	# check
+	if [[ $HDMI_STAT == connected ]]; then 
+		[[ ( ! -z "$CRSLT" && ! -z "$SRSLT" && ! -z "$PRSLT" ) ]] && switch "$CRSLT" "$SRSLT" "$PRSLT"
+	fi
 }
 
-volume() {
-
+setvolume() {
 	(( $# != 1 )) && printf "%s\n" "Please provide a volume level in percentage!" && exit 1
+
+	SINK_NAMES=($(pactl list sinks short | awk '{printf("%s\n", $2 )}'))
 
 	for i in ${SINK_NAMES[@]}; do
                pactl set-sink-volume "$i" "$1%"
 	done
 }
 
-device() {
-        printf "%s\n\n" "----| Current device |----"
+cards() {
+        printf "%s\n" "----| Card Names |----"
 
-	printf "%s\n%s\n%s\n%s\n%s\n"\
-	"Name: $(pactl list sinks short | awk '{ IGNORECASE = 1; printf "%s\n", (/running/ || /idle/ ? $2 : "N\\A") }')"\
-	"Current sink input number: $(pactl list sink-inputs short | awk 'BEGIN{ printf "%s\n", (NF!=0 ? $1 : "N\\A") }')"\
-	"Status of the sink: $(pactl list sinks short | awk '{ IGNORECASE = 1; printf "%s\n", (/running/ || /idle/ ? $7 : "SUSPENDED") }')"\
-	"Default Sink: $(pactl info | awk 'BEGIN {IGNORECASE=1} /default sink/ {print $3}')"\
-	"Default Source: $(pactl info | awk 'BEGIN {IGNORECASE=1} /default source/ {print $3}')" | column -t -s ":"
+	pactl list cards                                    | \
+		sed -n '/card #/I,/card_name/Ip'            | \
+		sed '/Driver/,/module/Id'                   | \
+		sed 's/^[ \t]*//'                           | \
+		column -t -s ":="                           | \
+		sed '/Card/i\\n'                            | \
+		sed '/Card/a..............'                 | \
+		sed '/Properties/Id'
+
 }
 
-list() {
-	printf "%s\n" "$(pactl list sinks short)"
+sinks() {
+        printf "\n\n%s\n" "----| Sink Names |----"
+
+	pactl list sinks                                    | \
+		sed -n '/sink #/I,/card_name/Ip'            | \
+		sed '/Driver/,/Properties/Id'               | \
+		sed '/description/I,/alsa.subclass/d'       | \
+		sed '/subdevice/d'                          | \
+		sed 's/^[ \t]*//'                           | \
+		column -t -s ":="                           | \
+		sed '/Sink/i\\n'                            | \
+		sed '/Sink/a..............'
+}
+
+volume() {
+        printf "\n\n%s\n\n" "----| Sink Volumes |----"
+
+	pactl list sinks                                    | \
+		sed -n '/Sink #/I, /.Volume/Ip'             | \
+		sed '/Description/,/Mute/d'                 | \
+		sed 's/^[ \t]*//'                           | \
+		sed 's/front[^%]*\///g'                     | \
+		sed 's/[/].*$//'                            | \
+		column -t                                   | \
+		sed '/Sink/a..............'                 | \
+		sed '/Volume/a\\n'
 }
 
 restart() {
@@ -98,54 +196,10 @@ restart() {
 	printf "%s\n" "Done!"
 }
 
-# param order:
-# param1 -> card name
-# param2 -> sink name
-# param3 -> profile
-initdevice() {
-	(( $# != 2 )) && "This function requires 3 arguments in a specific order!" && exit 1
-
-	for i in ${CARD_NAMES[@]}; do
-		[[ $i == $1 ]] && card="yes"
-	done
-
-
-	for i in ${SINK_NAMES[@]}; do
-		[[ $i == $2 ]] && sink="yes"
-	done
-
-	if [[ $card == "yes" ]] && [[ $sink == "yes" ]]; then 
-		pactl set-card-profile "$1" "$3"
-		pactl set-sink-volume "$2" 25% # ! IMPORTANT SO YOUR EAR DRUMS WON'T BLOW UP
-		pactl move-sink-input "$(getcurrentsink)" "$2"
-	else
-		printf "%s\n" "It seems there was an error with selecting either the card of the sink name!" && exit 1
-	fi
-}
-
 # get the profile names
 profiles() {
 	PROFILES=$(pactl list cards | awk '/Profiles/,/Active Profile/')
 	printf "%s\n" "$PROFILES"
-
-}
-
-# get specific sink name
-getsinkname() {
-	(( $# != 1 )) && printf "%s\n" "This function requires a part of the name of the sink you are looking for!" && exit 1
-	SINK_NAME=$(printf "%s\n" ${SINK_NAMES[@]} | awk -v device="$1" 'BEGIN {IGNORECASE=1} $1 ~ device')
-	printf "%s\n" "$SINK_NAME"
-}
-
-getcardname() {
-	(( $# != 1 )) && printf "%s\n" "This function requires a part of the name of the card you are looking for!" && exit 1
-	CARD_NAME=$(printf "%s\n" ${CARD_NAMES[@]} | awk -v device="$1" 'BEGIN {IGNORECASE=1} $1 ~ device')
-	printf "%s\n" "$CARD_NAME"
-}
-
-# get the current sink
-getcurrentsink() {
-	printf "%s\n" "$(pactl list sink-inputs short | awk 'NR==1 {print $1}')"
 }
 
 # EXECUTE, MAKE MY LIFE EASIER!
@@ -157,19 +211,21 @@ main() {
 	# check if arguments are provided
 	(( $# == 0 )) && usage  && exit 1
 
-	actions=("headphone" "speakers" "hdmi" "volume" "device" "list" "restart" "help")
+	actions=("external" "default" "hdmi" "volume" "cards" "sinks" "restart" "help" "profiles" "set-volume")
 
 	if (( $# == 1 )) || (( $# == 2 )); then
 		case "$1" in
-			headphone) headphone ;;
-			 speakers) speakers  ;;
-			     hdmi) hdmi      ;;
-			   volume) volume $2 ;;
-			   device) device    ;;
-			     list) list      ;;
-			 profiles) profiles  ;;
-			  restart) restart   ;;
-			        *) usage     ;;
+			 default)  default             ;;
+			     hdmi) hdmi                ;;
+			external*) external      $2    ;;
+		       set-volume) setvolume     $2    ;;
+		           volume) volume              ;;
+			    cards) cards               ;;
+			    sound) sound               ;;
+			    sinks) sinks               ;;
+			 profiles) profiles            ;;
+			  restart) restart             ;;
+			        *) usage               ;;
 		esac
 	fi
 
